export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CUSTOMER_PRODUCTS = "GET_CUSTOMER_PRODUCTS";
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER_PRODUCTS = "GET_ORDER_PRODUCTS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
